version: 0.0
os: linux

files:
  - source: /
    destination: /
  - source: appFiles.zip
    destination: /app/appFiles.zip

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 4755
hooks:
  BeforeInstall:
    - location: dummyScript.sh
      timeout: 300
      runas: root
    - location: beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: backend_run.sh
      timeout: 300
      runas: root