version: 0.0
os: linux

files:
  - source: /
    destination: ./webapp
permissions:
  - object: ./webapp
    pattern: "**"
    owner: root
    group: root
    mode: 4755
hooks:
  BeforeInstall:
    - location: ./webapp/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./webapp/backend_run.sh
      timeout: 300
      runas: root