version: 0.2
os: ubuntu

files:
  - source: ./backend
    destination: /backend
hooks:
  BeforeInstall:
    - location: dummyScript2.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: dummyScript.sh
      timeout: 30