version: 0.0
os: linux

files:
  - source: /
    destination: /opt/app
  # - source: appFiles.zip
  #   destination: /opt/app
file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/app
    pattern: "**"
    owner: root
    group: root
    mode: 4755

hooks:
  ApplicationStop:
    - location: backend_stop.sh
      timeout: 60
      runas: root
    - location: frontend_stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: installPackages.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: unzipApp.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: backend_start.sh
      timeout: 300
      runas: root
    - location: frontend_start.sh
      timeout: 300
      runas: root
    # - location: alg1_start.sh
    #   timeout: 300
    #   runas: root
    # - location: alg2_start.sh
    #   timeout: 300
    #   runas: root
  #ValidateService: