version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 4755
hooks:
  BeforeInstall:
    - location: dummyScript2.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: backend_run.sh
      timeout: 300
      runas: root