version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/backend
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: dummyScript2.sh
      timeout: 10
      runas: ec2-user
  AfterInstall:
    - location: dummyScript.sh
      timeout: 30
      runas: ec2-user