version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: dummyScript2.sh
      timeout: 10
      runas: ubuntu
  AfterInstall:
    - location: dummyScript.sh
      timeout: 30
      runas: ubuntu