version: 0.1
os: linux
files:
  - source: /
    destination: /webapps
hooks:
  BeforeInstall:
    - location: dummyScript.sh
      timeout: 300
  AfterInstall:
    - location: dummyScript.sh
      timeout: 30