version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 4755
hooks:
  BeforeInstall:
    - location: dummyScript2.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: dummyScript.sh
      timeout: 30
      runas: root