version: 0.0
os: linux

files:
  - source: /
    destination: /
  - source: /backend
    destination: /backend
  - source: /frontend
    destination: /frontend
  - source: /algorithm-1
    destination: /algorithm-1
  - source: /algorithm-2
    destination: /algorithm-2
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 4755
hooks:
  BeforeInstall:
    - location: dummyScript.sh
      timeout: 300
      runas: root
    - location: beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: backend_run.sh
      timeout: 300
      runas: root