version: 0.2
os: linux

files:
  - source: ./backend
    destination: /backend
hooks:
  ApplicationStop:
    - location: dummyScript.sh
      timeout: 10
  BeforeInstall:
    - location: dummyScript2.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: dummyScript.sh
      timeout: 30