version: 0.1

phases:
  install:
    commands:
      - echo Buildspec install phase
      - ls
      - pwd
  pre_build:
    commands:
      - echo Buildspec pre build phase
  build:
    commands:
      - echo Buildspec build phase
  post_build:
    commands:
      - echo Buildspec post build phase



