version: 0.1

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo Buildspec install phase
      - git clone https://github.com/SENG-499-Company-3/deploy.git
      - git submodule init
      - ls
      - ls backend
      - cd backend
      - pwd
  pre_build:
    commands:
      - echo Buildspec pre build phase
  build:
    commands:
      - echo Buildspec build phase
  post_build:
    commands:
      - echo Buildspec post build phase



