version: 0.0

phases:
  install:
    commands:
      - echo Cloning submodules
      - git clone -b dev https://github.com/SENG-499-Company-3/frontend.git
      - git clone -b dev https://github.com/SENG-499-Company-3/backend.git
      - git clone -b dev https://github.com/SENG-499-Company-3/algorithm-1.git
      - git clone -b dev https://github.com/SENG-499-Company-3/algorithm-2.git
  pre_build:
    commands:
      - echo Buildspec pre build phase
  build:
    commands:
      - echo Buildspec build phase
  post_build:
    commands:
      - echo Buildspec post build phase
      - ls

artifacts:
  files:
    - '**/*'

