version: 0.1

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo Buildspec install phase
      - aws codebuild import-source-credentials --cli-input-json file://import-source-credentials.json
      - aws codebuild list-source-credentials
      - ls
      - git submodule update --init --recursive
      - ls backend
      - cd backend
      - pwd
  pre_build:
    commands:
      - echo Buildspec pre build phase
  build:
    commands:
      - echo Buildspec build phase
  post_build:
    commands:
      - echo Buildspec post build phase



