version: 0.1

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo Buildspec install phase
      - ls
      - git clone -b dev https://github.com/SENG-499-Company-3/frontend.git
      - git clone -b dev https://github.com/SENG-499-Company-3/backend.git
      - git clone -b dev https://github.com/SENG-499-Company-3/algorithm-1.git
      - git clone -b dev https://github.com/SENG-499-Company-3/algorithm-2.git
      - ls
      - ls backend
      - cd backend
      - pwd
  pre_build:
    commands:
      - echo Buildspec pre build phase
  build:
    commands:
      - echo Buildspec build phase
  post_build:
    commands:
      - echo Buildspec post build phase



